### ISSUE TITLE
Add generation from seed string

### ISSUE THREAD

**Issue by cedvdb** [jlnrrg/avataaars#1]
It would be nice if it was possible to generate an avatar from a seed string

**Comment by jlnrrg** [comment]
Can you go a little more into detail:
- What do you hope to get out of this?
- How would you want to use it?
- Ideas how this could be implemented?
- There is a limited number of combinations, so what should happen, if there are no more new combinations?

**Comment by cedvdb** [comment]
The goal is to generate an avatar from an user uuid. If there are redundancy it does not matter, it's just an avatar.

**Comment by cedvdb** [comment]
> I would personally advice against this.
 > When you generate the avatar based on the uuid it can not be changed later

Those are not my requirements. My requirement is:

  - if the user does not have an image => use uuid to generate one
  - else use image.

**Comment by jlnrrg** [comment]
I see.
The easiest solution I see rn would be to add an additional parameter to the random() method.
So you could pass the Random functions seed. This would ensure that you each time get the some avatar for the same uuid.
An issue I see there would be that other users could get the same one on a different seed.
I am personally not familiar with programming a seed generator :sweat_smile:

**Comment by cedvdb** [comment]
Looking around for avatar libraries I found one in react that has a design language that is more in line with my app, so I guess I'll eventually try to port that one. So I'll close this, unless you want me to reopen.
